### ISSUE TITLE
Does not login

### ISSUE THREAD

**Issue by davidperezgar** [threesquared/PHP-Dynamics-Online-CRM-2011-SOAP-Class#1]
Hello, this class is seems to be deprecated, becouse MS is telling us to use Wildcards to login and use the API. Do you know this issue?

**Comment by threesquared** [comment]
Hi, sorry this project has become deprecated as I have not kept up to date with changes from Microsoft. Happy to review any pull requests if you know what needs to be modified? Otherwise please check the forks to see if there is a more up to date version.

**Comment by davidperezgar** [comment]
Ok, thanks for your comment.
