### ISSUE TITLE
Connect to CRM 2016 with ADFS authentication

### ISSUE THREAD

**Issue by mohammedabualsoud** [threesquared/PHP-Dynamics-Online-CRM-2011-SOAP-Class#2]
I need to authenticate with CRM 2016 app without existence of user, how to do that?

**Comment by threesquared** [comment]
Sorry this script is over five years old and for Dynamics 2011. Probably best to ask in the Dynamics CRM forum.

**Comment by mohammedabualsoud** [comment]
Why there are no standard lib to authenticate with any ADFS server in php?

**Comment by threesquared** [comment]
Sorry I don't know :neutral_face: maybe ask Microsoft?

**Comment by mohammedabualsoud** [comment]
ok thanks man I appreciate your response.
